services:
  - type: web
    name: social-media-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn social_media_api.wsgi --log-file -"
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "social-media-api.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://social-media-api.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: social-media-api-db
          property: connectionString

databases:
  - name: social-media-api-db
    databaseName: social_media_api
    user: social_media_api_user
